spring:
  application:
    name: bffweb-service
  cloud:
    bootstrap:
      enabled: true
    config:
      label: master
      name: config-server-bffweb_service
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://root:s3cr3t@config-server:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}