spring:
  application:
    name: bffweb-service
  cloud:
    bootstrap:
      enabled: true
    config:
      label: master
      name: config-server-bffweb_service
      username: tcero76
      password: '{cipher}e9287b2cb90b59c12135d7db3ed756f546e4fac22b9333ec017c03a9bc6c76bd'
  config:
    import: configserver:http://config-server:8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}