spring:
  application:
    name: gateway-service
  cloud:
    config:
      label: master
      name: config-server-gateway_service
  config:
    import: ${SPRING_CONFIG_IMPORT}
log:
  app-name: gateway-service
