server:
  port: ${PORT:8000}
  forward-headers-strategy: framework
container:
  hostname: ${HOSTNAME:auth-server}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
external:
  port: ${EXTERNAL_PORT}
postgres-config:
  url: jdbc:postgresql://localhost:5432/keycloak?currentSchema=payment
  username: keycloak
  password: keycloak
  schema: payment
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  show-sql: true
  stringtype: unspecified
public-key-location: ${PUBLICKEY}
private-key-location: ${PRIVATEKEY}