server:
  port: ${PORT:8000}
  forward-headers-strategy: framework
container:
  hostname: auth-server
external:
  port: ${EXTERNAL_PORT}
  host: ${EXTERNAL_HOST}
postgres-config:
  url: jdbc:postgresql://localhost:5432/keycloak?currentSchema=payment
  username: keycloak
  password: keycloak
  schema: payment
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  show-sql: true
  stringtype: unspecified
public-key-location: ${PUBLICKEY}
private-key-location: ${PRIVATEKEY}
logging:
  level:
    org:
      springframework:
        security: TRACE