server:
  port: ${PORT:8000}
  forward-headers-strategy: framework
container:
  hostname: ${HOSTNAME:auth-server}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus