/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package microservices

//import kotlin.test.Test
//import kotlin.test.assertNotNull
//
//class AppTest {
//    @Test fun appHasAGreeting() {
//        assertNotNull("app should have a greeting", "app should have a greeting")
//    }
//}
