version: '3.8'
services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    profiles:
      - monitoring
    hostname: grafana
    container_name: grafana
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - ${GLOBAL_NETWORK:-grafana}
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    profiles:
      - monitoring
    hostname: prometheus
    container_name: prometheus
    tty: true
    stdin_open: true
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      - ${GLOBAL_NETWORK:-prometheus}
  node_exporter:
    image: prom/node-exporter
    profiles:
      - monitoring
    container_name: node_exporter
    tty: true
    stdin_open: true
    ports:
      - "9100:9100"
    networks:
      - ${GLOBAL_NETWORK:-prometheus}
