version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    profiles:
      - base
      - db
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "5432:5432"
    networks:
      - ${GLOBAL_NETWORK}
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    profiles:
      - front
      - base
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=keycloak
    ports:
      - "9000:80"
    networks:
      - ${GLOBAL_NETWORK}