spring:
  application:
    name: resource-service
  cloud:
    bootstrap:
      enabled: true
    config:
      label: master
      name: config-server-resource_service
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}