spring:
  application:
    name: resource-service
  cloud:
    config:
      label: master
      name: config-server-resource_service
  config:
    import: ${SPRING_CONFIG_IMPORT}
log:
  app-name: resource-service

