spring:
  application:
    name: resource-service
  cloud:
    bootstrap:
      enabled: true
    config:
      label: master
      name: config-server-resource_service
      username: root
      password: '{cipher}63431c5252312f38049727f106137879cf3ca7abbdfabf0bfc4f11e3288d8929'
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}