server:
  port: 8081
spring:
  cloud:
    bootstrap:
      enabled: false
  sql:
    init:
      platform: postgres
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql
      mode: always
postgres-config:
  url: jdbc:postgresql://localhost:5432/keycloak?currentSchema=payment
  username: keycloak
  password: keycloak
  schema: payment
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  show-sql: true
  stringtype: unspecified
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
log:
  app-name: resource-service
public-key-location: ${PUBLICKEY}
logging:
  level:
    org:
      springframework:
        security: TRACE